### ISSUE TITLE
Could not find imported module support code

### ISSUE THREAD

**Issue by TheAngryByrd** [rtshome/ansible_pgsql#1]
Hey there!  I'm running into getting this role working.  I'm sure it's something stupid I'm doing. 

We're getting the error message:

```
FAILED! => {“failed”: true, “msg”: “Could not find imported module support code for postgresql_query.  Looked for either * or table”}
```

We followed the basic example setup https://github.com/rtshome/ansible_pgsql/wiki/Usage with the parameters and query set for our database.

```
---
- hosts: someserver
  tasks:
    - postgresql_query:
        database: somedatabase
        login_user: someuser
        login_password: somepassword
        query: select * from sometable
      register: query_results
  roles:
    - rtshome.pgsql
```

```
$ ansible --version
ansible 2.3.0

$ python --version
Python 2.7.9
```

Any advice?
